analyzer:
    plugins:
      - dart_code_metrics

dart_code_metrics:
  metrics-exclude:
    - test/**
    - lib/**/*.g.dart
    - lib/generated/**
  metrics:
    cyclomatic-complexity: 20
    number-of-arguments: 10
    maximum-nesting-level: 5
  rules-exclude:
    - test/**
    - lib/**/*.g.dart
    - lib/generated/**
  rules:
    - always-remove-listener
    - avoid-ignoring-return-values
    - avoid-nested-conditional-expressions
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-unused-parameters
    - avoid-wrapping-in-padding
    - double-literal-format
    - member-ordering
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-arguments
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-correct-type-name
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - listener
    - prefer-first
    - prefer-last
    - prefer-match-file-name
    - prefer-single-widget-per-file
    - prefer-trailing-comma
  anti-patterns:
    - long-method